export const COUNTRIES = [
  { code: 'AFG', name: 'Afghanistan' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'AUS', name: 'Australia' },
  { code: 'BEL', name: 'Belgium' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'BUL', name: 'Bulgaria' },
  { code: 'CAN', name: 'Canada' },
  { code: 'CHN', name: 'China', thaiName: 'จีน' },
  { code: 'COL', name: 'Colombia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'DOM', name: 'Dominican Republic', thaiName: 'โดมินิกัน' },
  { code: 'EGY', name: 'Egypt' },
  { code: 'FRA', name: 'France' },
  { code: 'GER', name: 'Germany' },
  { code: 'IRI', name: 'Iran' },
  { code: 'ITA', name: 'Italy', thaiName: 'อิตาลี' },
  { code: 'JPN', name: 'Japan', thaiName: 'ญี่ปุ่น' },
  { code: 'KOR', name: 'South Korea', thaiName: 'เกาหลีใต้' },
  { code: 'NED', name: 'Netherlands', thaiName: 'เนเธอร์แลนด์' },
  { code: 'POL', name: 'Poland' },
  { code: 'PUR', name: 'Puerto Rico' },
  { code: 'SRB', name: 'Serbia', thaiName: 'เซอร์เบีย' },
  { code: 'SLO', name: 'Slovenia' },
  { code: 'THA', name: 'Thailand', thaiName: 'ไทย' },
  { code: 'TUR', name: 'Turkey', thaiName: 'ตุรกี' },
  { code: 'USA', name: 'United States', thaiName: 'สหรัฐอเมริกา' },
  { code: 'VIE', name: 'Vietnam', thaiName: 'เวียดนาม' },
];
